### ISSUE TITLE
After log rotation, logs get bunched up and all dumped under one timestamp which is an hour and a half earlier

### ISSUE THREAD

**Issue by lando2319** [keymetrics/pm2-logrotate#195]
This is strange, I want to document it in the hope of clarity or a fix if it's needed

So it all started with me looking into a race condition to see if our event handler service was getting an event before we were saving the new transaction id.

Here is the log creating the transaction

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/db0576e3-f14c-411e-8334-77e50748b0a1" />

So here was the original transaction being created at 8:05

Searching the bus handler shows this

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/ca8f12af-0082-428d-9a6b-38fc17a37fce" />

It showed an event at 6:46, this was over an hour before the transaction was created.

These cloud logs run off our ops agent running on a google cloud vm instance. They monitor pm2 logs at the default location of, `~/.pm2/logs/*` 

By examining these logs and the entries before and after I can confirm this log entry happened at 8:05 NOT 6:46, I cannot find anything before.

So then I scrolled the logs without any search parameters and noticed hundreds and hundreds of entries with the same time of 6:46, our subscriber is only doing one at a time, so it's possible logging an obj might have it's elements logged at the same time, but otherwise these should not all be at the same time.

Eventually I reached the top of all the entries with the 6:46 time. And the log before this was the pm2 log rotation entry.

<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/43994831-b777-4c1d-a302-dd6696409c1e" />

I'm not sure what to make of this, I guess the log rotation caused the entries to bunch up and somehow get entered with a different timestamp over an hour before the event occurred.

I'm not sure. If anyone has any thoughts on this, is there some setting on the log rotator to avoid this. What is happening?

**Comment by lando2319** [comment]
So this ended up happening because of this line on our google ops agent config.yaml

`/etc/google-cloud-ops-agent/config.yaml`

We had the default builtin of this

```
logging:
  receivers:
    custom_file1:
      type: files
      include_paths:
      - /tmp/ops-*.log
  processors:
    parse_java_multiline:
      type: parse_multiline
      match_any:
      - type: language_exceptions
        language: java
    extract_structure:
      type: parse_regex
      field: message
      regex: "^(?<time>[\d-]*T[\d:.Z]*) (?<severity>[^ ]*) (?<file>[^ :]*):(?<line>[\d]*) - (?<message>(.|\\n)*)$"
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      pipeline1:
        receivers: [custom_file1]
        processors: [parse_java_multiline, extract_structure, move_severity]
```

But since we were not logging a time in the log entry, that was failing, which caused it to go to flush time which was causing the time to be off, and batched.

This as a config ended up solving the issue

```
logging:
  receivers:
    custom_file1:
      type: files
      include_paths:
      - /tmp/ops-*.log
  processors:
    parse_java_multiline:
      type: parse_multiline
      match_any:
      - type: language_exceptions
        language: java
  service:
    pipelines:
      pipeline1:
        receivers: [custom_file1]
        processors: [parse_java_multiline]
```

So in the end it had noting to do with pm2 log rotating
